import Link from 'next/link';
import { departments } from '@/services/departments';

const scenes = [
  { title: '团队协作', subtitle: '让信息自然流动', image: 'https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&w=700&q=80' },
  { title: '数据洞察', subtitle: '把复杂问题讲清楚', image: 'https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&w=700&q=80' },
  { title: '供应链现场', subtitle: '从库存到交付', image: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=700&q=80' },
  { title: '专注工作', subtitle: '让每个角色发挥所长', image: 'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=700&q=80' },
];

export default function Home() {
  const scrollingScenes = [...scenes, ...scenes];
  return <main className="home-page relative overflow-hidden bg-[#f8f9fb] text-[#202632]">
    <nav className="mx-auto flex h-[75px] max-w-6xl items-center justify-between px-5 sm:px-7">
      <Link href="/" className="flex items-center gap-2.5"><span className="agent-brand-mark flex h-9 w-9 items-center justify-center rounded-xl text-sm font-extrabold text-white">E</span><span><span className="block text-sm font-extrabold tracking-tight">ERGOLIFE</span><span className="mt-0.5 block text-[9px] uppercase tracking-[.1em] text-[#a5acb7]">Commerce intelligence</span></span></Link>
      <div className="flex items-center gap-4 text-[11px] text-[#808896] sm:gap-7"><a href="#about" className="hidden transition hover:text-[#087b61] sm:inline">关于我们</a><a href="#capabilities" className="hidden transition hover:text-[#087b61] sm:inline">能力中心</a><a href="#updates" className="hidden transition hover:text-[#087b61] sm:inline">动态</a><Link href="/logistics" className="rounded-lg bg-[#202632] px-3.5 py-2.5 font-bold text-white shadow-[0_7px_16px_rgba(32,38,50,.14)] transition hover:-translate-y-0.5 hover:bg-[#303746]">进入 Agent 工作区 →</Link></div>
    </nav>

    <section className="mx-auto grid max-w-6xl items-center gap-10 px-5 pb-16 pt-12 sm:px-7 sm:pt-16 lg:min-h-[490px] lg:grid-cols-2 lg:gap-14 lg:pb-20">
      <div><div className="inline-flex items-center gap-2 rounded-full border border-[#d4eee5] bg-white/65 px-2.5 py-1.5 text-[10px] font-bold text-[#087b61]"><span className="h-1.5 w-1.5 rounded-full bg-[#10a37f] shadow-[0_0_0_4px_rgba(16,163,127,.12)]" />面向电商团队的智能协作中枢</div><h1 className="mt-5 max-w-xl text-[clamp(38px,5vw,62px)] font-semibold leading-[1.08] tracking-[-.06em]">让每一次业务动作，<span className="text-[#087b61]">都更快落地。</span></h1><p className="mt-5 max-w-lg text-sm leading-7 text-[#7f8795]">ERGOLIFE 连接销售、库存、物流、运营与创意团队，把分散的数据、工具和经验，变成一套清晰可协作的工作流。</p><div className="mt-7 flex items-center gap-4"><Link href="/logistics" className="rounded-[10px] bg-[#10a37f] px-4 py-3 text-[11px] font-bold text-white shadow-[0_8px_17px_rgba(16,163,127,.2)] transition hover:-translate-y-0.5 hover:bg-[#087b61]">进入 Agent 工作区 →</Link><a href="#about" className="text-[11px] font-bold text-[#7d8694] transition hover:text-[#087b61]">了解 ERGOLIFE ↓</a></div></div>
      <div className="relative h-[315px] sm:h-[335px]"><div className="absolute right-0 top-5 h-[265px] w-[84%] overflow-hidden rounded-[23px] border-[7px] border-white/85 bg-[linear-gradient(135deg,rgba(25,57,65,.85),rgba(72,147,135,.86)),url('https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&w=1100&q=80')] bg-cover bg-center shadow-[0_22px_50px_rgba(41,63,72,.16)]"><div className="absolute inset-0 bg-gradient-to-br from-[#0d363a]/40 to-transparent" /><div className="absolute bottom-5 left-5 text-white"><strong className="block text-xl tracking-[-.04em]">From data to action</strong><span className="mt-1.5 block text-[10px] opacity-75">让洞察真正推动业务前进</span></div></div><div className="absolute left-0 top-0 flex items-center gap-2.5 rounded-[13px] border border-white/75 bg-white/95 p-3 shadow-[0_16px_32px_rgba(49,65,76,.14)]"><span className="flex h-8 w-8 items-center justify-center rounded-[9px] bg-[#e9f8f3] text-[#087b61]">✦</span><span><strong className="block text-[11px]">9 个部门</strong><small className="mt-0.5 block text-[9px] text-[#9ca3ae]">同一套协作体验</small></span></div><div className="absolute bottom-2 right-0 flex items-center gap-2.5 rounded-[13px] border border-white/75 bg-white/95 p-3 shadow-[0_16px_32px_rgba(49,65,76,.14)]"><span className="flex h-8 w-8 items-center justify-center rounded-[9px] bg-[#e9f8f3] text-[#087b61]">▤</span><span><strong className="block text-[11px]">工具驱动工作</strong><small className="mt-0.5 block text-[9px] text-[#9ca3ae]">连接数据 · 生成结果</small></span></div></div>
    </section>

    <section id="updates" className="border-y border-[#e9edf2] bg-white/70"><div className="mx-auto flex max-w-6xl items-center gap-5 px-5 py-4 sm:gap-7 sm:px-7"><div className="flex shrink-0 items-center gap-2 text-[10px] font-bold text-[#7b8492]"><span className="h-1.5 w-1.5 rounded-full bg-[#f0a548]" />实时动态</div><div className="flex gap-10 overflow-hidden whitespace-nowrap text-[10px] text-[#7d8693]"><span>物流销量同步与备货看板工具已上线</span><span>ERGOLIFE Agent Workspace 全新体验</span><span>从部门协作到商品全生命周期管理</span></div></div></section>

    <section id="about" className="mx-auto max-w-6xl px-5 py-20 sm:px-7"><div className="mb-7 flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><div className="text-[10px] font-extrabold uppercase tracking-[.11em] text-[#087b61]">About ERGOLIFE</div><h2 className="mt-2 text-3xl font-semibold tracking-[-.045em]">一个团队，一张业务全景图</h2></div><p className="max-w-sm text-[11px] leading-5 text-[#8a929e]">从商品机会到库存交付，让每个部门都能在自己的工作区里高效完成任务，也能共享同一份业务上下文。</p></div><div className="grid grid-cols-2 rounded-[17px] border border-[#e9edf2] bg-white shadow-[0_11px_35px_rgba(40,48,65,.045)] sm:grid-cols-4">{[['09', '专业部门工作区'], ['1', '统一协作入口'], ['22', '商品生命周期节点'], ['24/7', '持续运行的智能助手']].map(([value, label], index) => <div key={label} className={`p-5 sm:p-6 ${index < 2 ? 'border-b sm:border-b-0' : ''} ${index % 2 === 0 ? 'border-r' : 'sm:border-r'} ${index === 1 ? 'sm:border-r' : ''} ${index === 3 ? 'border-r-0' : ''} border-[#e9edf2]`}><strong className="block text-2xl tracking-[-.05em]">{value}</strong><span className="mt-1.5 block text-[10px] text-[#949ca8]">{label}</span></div>)}</div></section>

    <section id="capabilities" className="mx-auto max-w-6xl px-5 pb-20 sm:px-7"><div className="mb-7 flex items-end justify-between"><div><div className="text-[10px] font-extrabold uppercase tracking-[.11em] text-[#087b61]">Inside the work</div><h2 className="mt-2 text-3xl font-semibold tracking-[-.045em]">业务现场，正在发生</h2></div><p className="hidden max-w-sm text-[11px] leading-5 text-[#8a929e] sm:block">用一组组真实业务场景，串起团队每天的决策与执行。</p></div><div className="home-marquee flex gap-3.5">{scrollingScenes.map((scene, index) => <div key={`${scene.title}-${index}`} className="group relative h-[190px] w-[270px] shrink-0 overflow-hidden rounded-[15px] bg-[#c9deda] shadow-[0_12px_25px_rgba(40,48,65,.08)]"><div className="absolute inset-0 bg-cover bg-center transition duration-500 group-hover:scale-105" style={{ backgroundImage: `url(${scene.image})` }} /><div className="absolute inset-0 bg-gradient-to-b from-transparent via-transparent to-[#132126]/75" /><div className="absolute bottom-3.5 left-4 text-white"><strong className="block text-[13px]">{scene.title}</strong><span className="mt-1 block text-[9px] opacity-75">{scene.subtitle}</span></div></div>)}</div></section>

    <section className="mx-auto grid max-w-6xl gap-3 px-5 pb-20 sm:grid-cols-3 sm:px-7">{[['◈', '部门 Agent', '每个部门拥有自己的专业助手、聊天记录与任务上下文。'], ['⌘', '协作工作流', '从发现问题到执行工具，把分析和动作连接在同一个空间里。'], ['▤', '商品全链路', '围绕商品生命周期节点，让交接、提醒和状态更加清晰。']].map(([icon, title, text]) => <article key={title} className="rounded-[15px] border border-[#e9edf2] bg-white p-5 transition hover:-translate-y-1 hover:border-[#cfece2] hover:shadow-[0_15px_30px_rgba(40,48,65,.08)]"><div className="flex h-8 w-8 items-center justify-center rounded-[10px] bg-[#e9f8f3] text-[#087b61]">{icon}</div><h3 className="mt-4 text-[13px] font-bold">{title}</h3><p className="mt-1.5 text-[10px] leading-4 text-[#9098a4]">{text}</p></article>)}</section>
    <section className="mx-5 mb-16 rounded-[21px] bg-gradient-to-br from-[#edf9f5] to-[#f1effd] px-6 py-9 sm:mx-auto sm:max-w-[1104px] sm:px-12"><h2 className="max-w-md text-3xl font-semibold tracking-[-.045em]">准备好让团队更专注于重要的事了吗？</h2><p className="mt-2 max-w-lg text-[11px] leading-5 text-[#7f8795]">从一个部门开始，逐步建立适合 ERGOLIFE 的智能协作方式。</p><Link href="/logistics" className="mt-5 inline-block rounded-[10px] bg-[#10a37f] px-4 py-3 text-[11px] font-bold text-white shadow-[0_8px_17px_rgba(16,163,127,.2)] transition hover:bg-[#087b61]">进入 Agent 工作区 →</Link></section>
    <footer className="mx-auto flex max-w-6xl justify-between border-t border-[#e9edf2] px-5 py-6 text-[9px] text-[#aab1bc] sm:px-7"><span>© 2026 ERGOLIFE</span><span>Commerce intelligence workspace</span></footer>
  </main>;
}
